en, zh: add upgrade TiDB Operator offline
pingcap/docs-tidb-operator pull request #1200
Opened 2021-04-29 12:28 UTC by better0332

### What is changed, added, or deleted? (Required)

en, zh: add upgrade TiDB Operator offline

### Which TiDB Operator version(s) do your changes apply to? (Required)

- [* ] master (the latest development version)
- [ ] v1.1 (TiDB Operator 1.1 versions)
- [ ] v1.0 (TiDB Operator 1.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from: 
- Other reference link(s): 

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [* ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

2021-04-30 01:26 UTC, qiancai commented
/translation done

2021-04-30 01:27 UTC, qiancai commented
/cc @DanielZhangQD

2021-04-30 01:31 UTC, DanielZhangQD commented
/label needs-cherry-pick-1.1

2021-04-30 01:36 UTC, DanielZhangQD commented on zh/upgrade-tidb-operator.md
> +   如果服务器没有外网，需要先用有外网的机器下载 `crd.yaml` 文件，然后再进行安装：
单独一个 section 写离线升级吧，和 安装文档保持一致 https://docs.pingcap.com/zh/tidb-in-kubernetes/dev/deploy-tidb-operator#%E7%A6%BB%E7%BA%BF%E5%AE%89%E8%A3%85-tidb-operator

2021-04-30 03:07 UTC, qiancai commented
/status require-change

2021-04-30 08:09 UTC, better0332 commented
我已经改了

2021-04-30 08:32 UTC, DanielZhangQD reviewed
Rest LGTM

2021-04-30 08:32 UTC, DanielZhangQD commented on zh/upgrade-tidb-operator.md
> +如果服务器没有外网，需要按照下面的步骤来离线安装 TiDB Operator：
```suggestion
如果服务器没有外网，需要按照下面的步骤来离线升级 TiDB Operator：
```

2021-04-30 08:32 UTC, DanielZhangQD commented on zh/upgrade-tidb-operator.md
> +   > `${version}` 在后续文档中代表 TiDB Operator 版本，例如 `v1.2.0-beta.1`，可以通过 `helm search repo -l tidb-operator` 查看当前支持的版本。
```suggestion
   > `${version}` 在后续文档中代表 TiDB Operator 版本，例如 `v1.2.0-beta.2`，可以通过 `helm search repo -l tidb-operator` 查看当前支持的版本。
```

2021-05-04 07:17 UTC, better0332 commented
> @better0332, please update your pull request.

alreday updated

2021-05-06 02:21 UTC, qiancai requested changes

2021-05-06 02:21 UTC, qiancai commented on zh/upgrade-tidb-operator.md
> +   > `${version}` 在后续文档中代表 TiDB Operator 版本，例如 `v1.2.0-beta.2`，可以通过 `helm search repo -l tidb-operator` 查看当前支持的版本。
```suggestion
   > `${version}` 在本文中代表 TiDB Operator 版本，例如 `v1.2.0-beta.2`。你可以通过 `helm search repo -l tidb-operator` 命令查看当前支持的版本。
```

2021-05-06 02:21 UTC, qiancai commented on zh/upgrade-tidb-operator.md
> +   > 如果未包含最新版本，可以通过 `helm repo update` 更新 repo。详情请参考[配置 Helm repo](tidb-toolkit.md#配置-helm-repo) )。
```suggestion
   > 如果此命令的输出中未包含最新版本，可以通过 `helm repo update` 更新 repo。详情请参考[配置 Helm repo](tidb-toolkit.md#配置-helm-repo) 。
```

2021-05-06 02:21 UTC, qiancai commented on zh/upgrade-tidb-operator.md
> +3. 在有外网的机器上将 `operatorImage` 镜像版本下载下来并上传到服务器上，然后使用 `docker load` 将 Docker 镜像安装到服务器上（详情请参考[下载 TiDB Operator 运行所需的 Docker 镜像](deploy-tidb-operator.md)），然后通过以下命令升级：
https://github.com/pingcap/docs-tidb-operator/blob/bc96120c965a25072c1d8135686ac2f4681edd7c/zh/deploy-tidb-operator.md  这里的 step 2 里没有提到有 `operatorImage` 镜像呢？ 请问，`operatorImage` 镜像也是使用 docker pull 的方法下载吗？

2021-05-06 02:21 UTC, qiancai commented on en/upgrade-tidb-operator.md
> +   > After TiDB Operator is upgraded, the `discovery` deployment in all TiDB clusters will automatically upgrade to the specified version of TiDB Operator.
```suggestion
   > After TiDB Operator is upgraded, the `discovery` deployment in all TiDB clusters will be automatically upgraded to the specified version of TiDB Operator.
```

2021-05-11 16:03 UTC, qiancai commented on zh/upgrade-tidb-operator.md
> +   > TiDB Operator 升级之后，所有 TiDB 集群中的 `discovery` deployment 都会自动升级到指定的 TiDB Operator 版本。
```suggestion
   > TiDB Operator 升级之后，所有 TiDB 集群中的 `discovery` deployment 都会自动升级到对应的 TiDB Operator 版本。
```

2021-05-12 04:43 UTC, qiancai commented on zh/upgrade-tidb-operator.md
> +1. 更新 Kubernetes 的 CustomResourceDefinition (CRD)。关于 CRD 的更多信息，请参阅 [CustomResourceDefinition](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/)：
```suggestion
1. 更新 Kubernetes 的 CustomResourceDefinition (CRD)。关于 CRD 的更多信息，请参阅 [CustomResourceDefinition](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/)。
```

2021-05-13 01:22 UTC, qiancai commented on en/upgrade-tidb-operator.md
> +## Offline Upgrade TiDB Operator
PTAL. Thanks.

2021-05-19 02:14 UTC, DanielZhangQD commented on zh/upgrade-tidb-operator.md
> +    > `${version}` 在本文中代表 TiDB Operator 版本，例如 `v1.2.0-beta.2`。你可以通过 `helm search repo -l tidb-operator` 命令查看当前支持的版本。
把这个文档里面的命令里面的 ${version} 直接替换成当前版本吧，这样用户复制就可以直接用

2021-05-19 02:14 UTC, DanielZhangQD commented on zh/upgrade-tidb-operator.md
> +    > 如果此命令的输出中未包含最新版本，可以通过 `helm repo update` 更新 repo。详情请参考[配置 Helm repo](tidb-toolkit.md#配置-helm-repo) 。
```suggestion
    > 你可以通过 `helm search repo -l tidb-operator` 命令查看当前支持的版本。
    > 如果此命令的输出中未包含最新版本，可以通过 `helm repo update` 更新 repo。详情请参考[配置 Helm repo](tidb-toolkit.md#配置-helm-repo) 。
```

2021-05-19 02:18 UTC, DanielZhangQD commented on zh/upgrade-tidb-operator.md
> +    > 如果此命令的输出中未包含最新版本，可以使用 `helm repo update` 命令更新 repo。详情请参考[配置 Helm repo](tidb-toolkit.md#配置-helm-repo) 。
这里和 L22-L25 重复了，抽离出来放到文档开头吧，在这两个小节外面。

2021-05-19 02:19 UTC, DanielZhangQD commented on zh/upgrade-tidb-operator.md
> +    kubectl apply -f ./crd.yaml && \
```suggestion
    kubectl apply -f ./crd.yaml
```

2021-05-19 11:01 UTC, DanielZhangQD commented on zh/upgrade-tidb-operator.md
> +   输出类似下方结果则表示升级成功，`${version}`表示要升级到的版本号。
这里 version 也都改掉吧

2021-05-19 11:01 UTC, DanielZhangQD commented on zh/upgrade-tidb-operator.md
> + > `${version}` 在本文中代表 TiDB Operator 版本，例如 `v1.2.0-beta.2`。你可以通过 `helm search repo -l tidb-operator` 命令查看当前支持的版本。
```suggestion
 > 你可以通过 `helm search repo -l tidb-operator` 命令查看当前支持的 TiDB Operator 版本。
```

2021-05-19 11:02 UTC, DanielZhangQD commented on zh/upgrade-tidb-operator.md
> +   输出类似下方结果则表示升级成功，`${version}`表示要升级到的版本号。
看下文档其他地方，都改掉吧

2021-05-19 11:40 UTC, qiancai commented on zh/upgrade-tidb-operator.md
> +1. 使用有外网的机器下载升级所需的文件和镜像
```suggestion
1. 使用有外网的机器下载升级所需的文件和镜像。
```

2021-05-19 11:40 UTC, qiancai commented on zh/upgrade-tidb-operator.md
> +    3. 下载 TiDB Operator 升级所需的以下 Docker 镜像:
```suggestion
    3. 下载 TiDB Operator 升级所需的 Docker 镜像:
```

2021-05-19 11:40 UTC, qiancai commented on zh/upgrade-tidb-operator.md
> +2. 上传并安装下载的文件和镜像到需要升级的服务器上
```suggestion
2. 上传并安装下载的文件和镜像到需要升级的服务器上。
```

2021-05-19 11:40 UTC, qiancai commented on zh/upgrade-tidb-operator.md
> +    3. 安装 Docker 镜像安装到服务器上：
```suggestion
    3. 安装 Docker 镜像到服务器上：
```

2021-05-20 03:07 UTC, qiancai commented on zh/upgrade-tidb-operator.md
> +2. 上传并安装下载的文件和镜像到需要升级的服务器上。
```suggestion
2. 将下载的文件和镜像上传到需要升级的服务器上，然后按照以下步骤进行安装：
```

2021-05-20 03:07 UTC, qiancai commented on en/upgrade-tidb-operator.md
> +    ```
```suggestion
2. Upload the downloaded files and images to the server that needs to be upgraded, and then take the following steps for installation:

    1. Install the `crd.yaml` file for TiDB Operator:

    {{< copyable "shell-regular" >}}

    ```shell
    kubectl apply -f . /crd.yaml
    ```

    2. Unpack the `tidb-operator` chart package file, and then copy the `values.yaml` file:

    {{< copyable "shell-regular" >}}

    ```shell
    tar zxvf tidb-operator-v1.2.0-beta.2.tgz && \
    mkdir -p ${HOME}/tidb-operator/v1.2.0-beta.2 &&
    cp tidb-operator/values.yaml ${HOME}/tidb-operator/v1.2.0-beta.2/values-tidb-operator.yaml
    ```

    3. Install the Docker image on the server:

    {{< copyable "shell-regular" >}}

    ```shell
    docker load -i tidb-operator-v1.2.0-beta.2.tar
    docker load -i tidb-backup-manager-v1.2.0-beta.2.tar
    ```
```

2021-05-20 03:07 UTC, qiancai commented on en/upgrade-tidb-operator.md
> +
```suggestion
```

2021-05-20 03:07 UTC, qiancai commented on en/upgrade-tidb-operator.md
> +4. In the `${HOME}/tidb-operator/${version}/values-tidb-operator.yaml` file, modify the `operatorImage` version to the new TiDB Operator version. Merge the customized configuration in the old `values
```suggestion
3. In the `${HOME}/tidb-operator/${version}/values-tidb-operator.yaml` file, modify the `operatorImage` version to the new TiDB Operator version. Merge the customized configuration in the old `values.yaml` file to the `${HOME}/tidb-operator/${version}/values-tidb-operator.yaml` file, and then execute `helm upgrade`:
```

2021-05-20 03:07 UTC, qiancai commented on en/upgrade-tidb-operator.md
> +    helm upgrade tidb-operator ./tidb-operator --version=${version} -f ${HOME}/tidb-operator/${version}/values-tidb-operator.yaml
```suggestion
    helm upgrade tidb-operator ./tidb-operator --version=v1.2.0-beta.2 -f ${HOME}/tidb-operator/v1.2.0-beta.2/values-tidb-operator.yaml
```

2021-05-20 15:05 UTC, qiancai commented on en/upgrade-tidb-operator.md
> +2. Get the `values.yaml` file of the `tidb-operator` chart for the new version of TiDB Operator.
```suggestion
2. Get the `values.yaml` file of the `tidb-operator` chart for the new TiDB Operator version. 
```

2021-05-20 15:05 UTC, qiancai commented on en/upgrade-tidb-operator.md
> +    3. Download the Docker image required for the new TiDB Operator version:
```suggestion
    3. Download the Docker images required for the new TiDB Operator version:
```

2021-05-20 15:05 UTC, qiancai commented on en/upgrade-tidb-operator.md
> +    docker save -o tidb-operator-v1.2.0-beta.2.tar pingcap/tidb-operator:v1.2.0-beta.2
```suggestion

    docker save -o tidb-operator-v1.2.0-beta.2.tar pingcap/tidb-operator:v1.2.0-beta.2
```

2021-05-20 15:05 UTC, qiancai commented on en/upgrade-tidb-operator.md
> +    3. Install the Docker image on the server:
```suggestion
    3. Install the Docker images on the server:
```

2021-05-20 15:05 UTC, qiancai commented on en/upgrade-tidb-operator.md
> +    > After TiDB Operator is upgraded, the `discovery` deployment in all TiDB clusters will be automatically upgraded to the specified version of TiDB Operator.
```suggestion
    > After TiDB Operator is upgraded, the `discovery` deployment in all TiDB clusters will be automatically upgraded to the corresponding version of TiDB Operator.
```

2021-05-20 15:07 UTC, qiancai commented on en/upgrade-tidb-operator.md
> +2. Get the `values.yaml` file of the `tidb-operator` chart for the new version of TiDB Operator.
```suggestion
2. Get the `values.yaml` file of the `tidb-operator` chart for the TiDB Operator version.
```

2021-05-24 01:41 UTC, qiancai commented on en/upgrade-tidb-operator.md
> +    ```
```suggestion
        {{< copyable "shell-regular" >}}

        ```shell
        wget http://charts.pingcap.org/tidb-operator-v1.2.0-beta.2.tgz
        ```
```

2021-05-24 02:21 UTC, TomShawn commented on en/upgrade-tidb-operator.md
> +    ```
8 indentations are needed.

2021-05-24 02:22 UTC, TomShawn commented on en/upgrade-tidb-operator.md
> +    ```
```suggestion
8 indentations are needed.
```

2021-05-24 02:34 UTC, qiancai commented on zh/upgrade-tidb-operator.md
> +    ```
```suggestion
    1. 下载 TiDB Operator 需要的 `crd.yaml` 文件。关于 CRD 的更多信息，请参阅 [CustomResourceDefinition](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/)。
   
        {{< copyable "shell-regular" >}}

        ```shell
        wget https://raw.githubusercontent.com/pingcap/tidb-operator/v1.2.0-beta.2/manifests/crd.yaml
        ```

    2. 下载 `tidb-operator` chart 包文件：

        {{< copyable "shell-regular" >}}

        ```shell
        wget http://charts.pingcap.org/tidb-operator-v1.2.0-beta.2.tgz
        ```
```

2021-05-24 02:34 UTC, qiancai commented on zh/upgrade-tidb-operator.md
> +    ```
```suggestion
    3. 下载 TiDB Operator 升级所需的 Docker 镜像:

        {{< copyable "shell-regular" >}}

        ```shell
        docker pull pingcap/tidb-operator:v1.2.0-beta.2
        docker pull pingcap/tidb-backup-manager:v1.2.0-beta.2

        docker save -o tidb-operator-v1.2.0-beta.2.tar pingcap/tidb-operator:v1.2.0-beta.2
        docker save -o tidb-backup-manager-v1.2.0-beta.2.tar pingcap/tidb-backup-manager:v1.2.0-beta.2
        ```
```

2021-05-24 02:34 UTC, qiancai commented on zh/upgrade-tidb-operator.md
> +    ```
```suggestion
    1. 安装 TiDB Operator 需要的 `crd.yaml` 文件：

        {{< copyable "shell-regular" >}}

        ```shell
        kubectl apply -f ./crd.yaml
        ```

    2. 解压 `tidb-operator` chart 包文件，并拷贝 `values.yaml` 文件：

        {{< copyable "shell-regular" >}}

        ```shell
        tar zxvf tidb-operator-v1.2.0-beta.2.tgz && \
        mkdir -p ${HOME}/tidb-operator/v1.2.0-beta.2 && \
        cp tidb-operator/values.yaml ${HOME}/tidb-operator/v1.2.0-beta.2/values-tidb-operator.yaml
        ```
```

2021-05-24 02:34 UTC, qiancai commented on zh/upgrade-tidb-operator.md
> +    ```
```suggestion
    3. 安装 Docker 镜像到服务器上：

        {{< copyable "shell-regular" >}}

        ```shell
        docker load -i tidb-operator-v1.2.0-beta.2.tar
        docker load -i tidb-backup-manager-v1.2.0-beta.2.tar
        ```
```

2021-05-24 02:34 UTC, qiancai commented on en/upgrade-tidb-operator.md
> +    ```
```suggestion
        {{< copyable "shell-regular" >}}

        ```shell
        wget https://raw.githubusercontent.com/pingcap/tidb-operator/v1.2.0-beta.2/manifests/crd.yaml
        ```
```

2021-05-24 02:34 UTC, qiancai commented on en/upgrade-tidb-operator.md
> +    ```
```suggestion
        {{< copyable "shell-regular" >}}
    
        ```shell
        docker pull pingcap/tidb-operator:v1.2.0-beta.2
        docker pull pingcap/tidb-backup-manager:v1.2.0-beta.2

        docker save -o tidb-operator-v1.2.0-beta.2.tar pingcap/tidb-operator:v1.2.0-beta.2
        docker save -o tidb-backup-manager-v1.2.0-beta.2.tar pingcap/tidb-backup-manager:v1.2.0-beta.2
        ```
```

2021-05-24 02:34 UTC, qiancai commented on en/upgrade-tidb-operator.md
> +    ```
```suggestion
        {{< copyable "shell-regular" >}}

        ```shell
        kubectl apply -f . /crd.yaml
        ```
```

2021-05-24 02:34 UTC, qiancai commented on en/upgrade-tidb-operator.md
> +    ```
```suggestion
        {{< copyable "shell-regular" >}}

        ```shell
        tar zxvf tidb-operator-v1.2.0-beta.2.tgz && \
        mkdir -p ${HOME}/tidb-operator/v1.2.0-beta.2 &&
        cp tidb-operator/values.yaml ${HOME}/tidb-operator/v1.2.0-beta.2/values-tidb-operator.yaml
        ```

    3. Install the Docker images on the server:

        {{< copyable "shell-regular" >}}

        ```shell
        docker load -i tidb-operator-v1.2.0-beta.2.tar
        docker load -i tidb-backup-manager-v1.2.0-beta.2.tar
        ```
```

2021-05-24 02:52 UTC, qiancai commented
/lgtm

2021-05-24 03:29 UTC, DanielZhangQD approved these changes
LGTM

2021-05-24 03:30 UTC, DanielZhangQD commented
/merge

2021-05-24 03:31 UTC, merged